package generator

import (
	"go/ast"
	"go/parser"
	"go/token"
	"path/filepath"
	"strings"
)

// EntityField represents a single parsed struct field with its SQL mapping.
type EntityField struct {
	Name    string // Go field name
	SQLName string // snake_case column name
	SQLType string // SQL type string
}

// ParseEntityFields reads internal/domain/entity/{snake}.go and returns
// the fields of the first exported struct found, mapped to SQL types.
// Returns nil if the file does not exist or cannot be parsed — callers
// fall back to the skeleton template.
func ParseEntityFields(snake string) []EntityField {
	path := filepath.Join("internal", "domain", "entity", snake+".go")
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, path, nil, 0)
	if err != nil {
		return nil
	}

	for _, decl := range f.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.TYPE {
			continue
		}
		for _, spec := range gen.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			st, ok := ts.Type.(*ast.StructType)
			if !ok || !ts.Name.IsExported() {
				continue
			}
			return extractFields(st)
		}
	}
	return nil
}

// skipFields are GORM base columns generated by the skeleton template.
var skipFields = map[string]bool{
	"ID": true, "CreatedAt": true, "UpdatedAt": true, "DeletedAt": true,
}

func extractFields(st *ast.StructType) []EntityField {
	var fields []EntityField
	for _, f := range st.Fields.List {
		if len(f.Names) == 0 {
			continue // embedded field
		}
		name := f.Names[0].Name
		if !f.Names[0].IsExported() || skipFields[name] {
			continue
		}
		col := toSnake(name)
		sqlType := goTypeToSQL(f.Type)
		fields = append(fields, EntityField{Name: name, SQLName: col, SQLType: sqlType})
	}
	return fields
}

func goTypeToSQL(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return identToSQL(t.Name)
	case *ast.SelectorExpr:
		// e.g. uuid.UUID, time.Time
		if id, ok := t.X.(*ast.Ident); ok {
			return selectorToSQL(id.Name, t.Sel.Name)
		}
	case *ast.StarExpr:
		// pointer — recurse, result is nullable
		return goTypeToSQL(t.X)
	case *ast.ArrayType:
		return "JSON"
	}
	return "TEXT"
}

func identToSQL(name string) string {
	switch name {
	case "string":
		return "VARCHAR(255) NOT NULL"
	case "int", "int32":
		return "INT NOT NULL DEFAULT 0"
	case "int64":
		return "BIGINT NOT NULL DEFAULT 0"
	case "uint", "uint32":
		return "INT UNSIGNED NOT NULL DEFAULT 0"
	case "uint64":
		return "BIGINT UNSIGNED NOT NULL DEFAULT 0"
	case "float32", "float64":
		return "DECIMAL(18,4) NOT NULL DEFAULT 0"
	case "bool":
		return "TINYINT(1) NOT NULL DEFAULT 0"
	default:
		return "TEXT"
	}
}

func selectorToSQL(pkg, typ string) string {
	switch pkg + "." + typ {
	case "uuid.UUID":
		return "VARCHAR(36) NOT NULL"
	case "time.Time":
		return "TIMESTAMP(3) NOT NULL"
	case "decimal.Decimal", "decimal.NullDecimal":
		return "DECIMAL(18,4) NOT NULL DEFAULT 0"
	case "null.String", "sql.NullString":
		return "VARCHAR(255) NULL"
	case "null.Time", "sql.NullTime":
		return "TIMESTAMP(3) NULL"
	case "null.Int64", "sql.NullInt64":
		return "BIGINT NULL"
	case "null.Bool", "sql.NullBool":
		return "TINYINT(1) NULL"
	case "gorm.DeletedAt":
		return "" // skip — already in skeleton
	default:
		return "TEXT"
	}
}

// RenderMigrationColumns renders the SQL column lines for an entity's fields.
// Returns the skeleton comment if no fields are found.
func RenderMigrationColumns(fields []EntityField) string {
	if len(fields) == 0 {
		return "    -- TODO: add domain columns here"
	}
	var sb strings.Builder
	for _, f := range fields {
		if f.SQLType == "" {
			continue
		}
		sb.WriteString("    ")
		sb.WriteString(f.SQLName)
		// pad column name to 12 chars for alignment
		pad := 12 - len(f.SQLName)
		if pad > 0 {
			sb.WriteString(strings.Repeat(" ", pad))
		} else {
			sb.WriteByte(' ')
		}
		sb.WriteString(f.SQLType)
		sb.WriteString(",\n")
	}
	result := sb.String()
	// trim trailing newline so the caller controls spacing
	return strings.TrimRight(result, "\n")
}
