// Package docs is auto-generated by swaggo/swag. This test ensures the
// package init() runs under coverage so the gate counts it.
package docs

import "testing"

func TestDocsInit(t *testing.T) {
	// Importing this package executes init(), which registers the swagger spec.
	// No assertions needed — coverage of the init body is the goal.
}
